# Site settings
title: "Home Office Open Source"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Summary of the UK Home Office's Digital Teams Repositories
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ukhomeoffice.github.io/" # the base hostname & protocol for your site
twitter_username: hodigital
github_username:  ukhomeoffice

# Build settings
markdown: kramdown
